---
- hosts: 172.31.17.135
  become: yes
  tasks:
     - include_tasks: myfile.yml
      
     - name: install apache2
       apt: 
           name: apache2
           state: present

     - name: i want to create file or copy file or alter file
       template:
        src: myindex.j2
        dest: /var/www/html/index.html